[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
loglevel=info

[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=http://127.0.0.1:9001

[inet_http_server]
port = 0.0.0.0:9001

[program:kinhdoanh]
command=python kinhdoanh.py
directory=/process
autostart=true
autorestart=unexpected
stdout_logfile=/var/log/supervisor/kinhdoanh/%(program_name)s.log

[program:tintucmoi]
command=python tintucmoi.py
directory=/process
autostart=true
autorestart=unexpected
stdout_logfile=/var/log/supervisor/tintucmoi/%(program_name)s.log


[program:giaitri]
command=python giaitri.py   
directory=/process
autostart=true
autorestart=unexpected
stdout_logfile=/var/log/supervisor/giaitri/%(program_name)s.log

[program:initializeDB]
command=python initializeDB.py   
directory=/process
autostart=true
autorestart=unexpected
stdout_logfile=/var/log/supervisor/initializeDB/%(program_name)s.log
